---
title: "과제3"
author: "1602108 정유진"
date: "2018년 10월 29일"
output: word_document
---

# 데이터 불러오기 및 변수생성

```{r}
hmada.data<-read.csv("C:\\Temp\\hmda.csv",header=TRUE)
attach(hmada.data)
pi_rat<-s46/100                                      # P/I ratio
hse_inc<-s45/100                                     # housing expense-to-income ratio
ltv<-s6/s50                                          # loan-to-value ratio
ccred<-s43                                           # consumer credit score
mcred<-s42                                           # mortgage credit score
pubrec<-s44                                          # public bad credit record
denpmi<-s53                                          # denied mortgage insurance
selfemp<-s27a                                        # self-employed
single<-ifelse(s23a=="U",1,0)
hischl<-ifelse(school>=12,1,0)                       # high school diploma              
condo<-ifelse(s51==1,1,0)                            # condominium
black<-ifelse(s13==3,1,0)                 
deny<-ifelse(s7==3,1,0)
ltv_med<-ifelse(ltv>=0.85 & ltv<0.95,1,0)
ltv_high<-ifelse(ltv>=0.95,1,0)

mortdeny.data<-data.frame(pi_rat=pi_rat,hse_inc=hse_inc,ccred=ccred,mcred=mcred,pubrec=pubrec,denpmi=denpmi,selfemp=selfemp,single=single,hischl=hischl,condo=condo,black=black,deny=deny,ltv_high=ltv_high,ltv_med=ltv_med)
```

# 모형 만들기

```{r}
logit.model = glm(deny~black+pi_rat+hse_inc+ltv_med+ltv_high+ccred+mcred+pubrec+denpmi+selfemp+single+hischl, family=binomial(link="logit"))
summary(logit.model)
```

# 오즈비 추정

```{r}
coefficients(logit.model)
colMeans(mortdeny.data) 
```

## 흑인의 오즈비

```{r}
proreject<-1/(1+exp(-( -4.5252736+4.8085698*0.33081357-0.3481660*0.25534612+0.2451080*0.24663866+1.3595221*0.03403361+0.2954694*2.11638655+0.2543477*1.72100840+1.2716920*0.07352941+4.5718757*0.02016807+ 0.6911721*0.11638655+0.4552889*0.36176471-1.1887378*0.98361345+0.6587446*1)))
oz_black<-proreject/(1-proreject)
```

## 백인의 오즈비

```{r}
proreject2<-1/(1+exp(-(-4.5252736+4.8085698*0.33081357-0.3481660*0.25534612+0.2451080*0.24663866+1.3595221*0.03403361+0.2954694*2.11638655+0.2543477*1.72100840+1.2716920*0.07352941+4.5718757*0.02016807+ 0.6911721*0.11638655+0.4552889*0.36176471-1.1887378*0.98361345+0.6587446*0)))
oz_white<-proreject2/(1-proreject2)
```

## 백인 대비 흑인 오즈비
```{r}
oz_black/oz_white
exp(0.6587446)
```

